name: acanthis
description: Acanthis is an easy-to-use validation library for Dart and Flutter.
version: 1.0.2
homepage: https://acanthis.avesbox.com
documentation: https://acanthis.avesbox.com/introduction.html
repository: https://github.com/avesbox/acanthis
funding:
  - https://github.com/sponsors/francescovallone

topics:
  - validation
  - dart
  - validation-form
  - validators
  - zod


environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  email_validator: ^3.0.0
  crypto: ^3.0.0
  fast_immutable_collections: ^11.0.4
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
